# Generated by Django 4.0.3 on 2022-04-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='test', max_length=125),
            preserve_default=False,
        ),
    ]
